export enum Routes {
  HomePage = "/",
  Login = "/login",
  Equipments = "/equipments",
  EquipmentsNew = "/equipments/new",
  EquipmentsEdit = "/equipments/[id]/edit",
  Equipment = "/equipments/[id]",
  ConsumerUnits = "/consumer-unit",
  ConsumerUnit = "/consumer-unit/[id]",
  ConsumerUnitNew = "/consumer-unit/new",
  ConsumerUnitEdit = "/consumer-unit/[id]/edit",
  Concessionaires = "/concessionaire",
  Concessionaire = "/concessionaire/[id]",
  ConcessionaireNew = "/concessionaire/new",
  ConfirmEmail = "/confirm-email",
  NoPermission = "/no-permission",
  Register = "/register",
  RecoverPasswordByEmail = "/recover-password/email",
  MainPage = ConsumerUnits,
}
