export enum Routes {
  HomePage = "/",
  Login = "/login",
  Equipments = "/equipments",
  EquipmentsNew = "/equipments/new",
  EquipmentsEdit = "/equipments/[id]/edit",
  Equipment = "/equipments/[id]",
  ConsumerUnits = "/consumer-units",
  ConsumerUnit = "/consumer-units/[id]",
  ConsumerUnitNew = "/consumer-units/new",
  ConsumerUnitEdit = "/consumer-units/[id]/edit",
  Concessionaires = "/concessionaires",
  Concessionaire = "/concessionaires/[id]",
  ConcessionaireEdit = "/concessionaires/[id]/edit",
  ConcessionaireNew = "/concessionaires/new",
  Users = "/users",
  User = "/users/[id]",
  AdminNew = "/users/new",
  UserEdit = "/users/[id]/edit",
  ConfirmEmail = "/confirm-email",
  NoPermission = "/no-permission",
  Register = "/register",
  RecoverPasswordByEmail = "/recover-password/email",
  MainPage = ConsumerUnits,
}
