export enum Routes {
  HomePage = "/",
  Login = "/login",
  Equipments = "/equipments",
  EquipmentsNew = "/equipments/new",
  EquipmentsEdit = "/equipments/[id]/edit",
  Equipment = "/equipments/[id]",
  ConsumerUnit = "/consumer-unit",
  ConsumerUnitNew = "/consumer-unit/new",
  ConfirmEmail = "/confirm-email",
  NoPermission = "/no-permission",
  Register = "/register",
  RecoverPasswordByEmail = "/recover-password/email",
  MainPage = ConsumerUnit,
}
