import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/providers/react-query.provider";
import { CookiesProvider } from "next-client-cookies/server";
import { AlertProvider } from "@/providers/alert.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Smart Click",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CookiesProvider>
          <Providers>
            <AlertProvider>
              <>
                {children}
                <Toaster />
              </>
            </AlertProvider>
          </Providers>
        </CookiesProvider>
      </body>
    </html>
  );
}
